twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig'] # Définit un thème par défaut pour le design de nos formulaires
when@test:
    twig:
        strict_variables: true
